"""add_sale_order_id_to_third_party_sale

Revision ID: 86677ff09934
Revises: c797da3c3437
Create Date: 2026-03-28 20:36:26.710200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86677ff09934'
down_revision: Union[str, None] = 'c797da3c3437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
