"""add_third_party_sale_table

Revision ID: c797da3c3437
Revises: 35b979a27a51
Create Date: 2026-03-28 18:35:20.325495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c797da3c3437'
down_revision: Union[str, None] = '35b979a27a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('third_party_sale', sa.Column('buying_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('third_party_sale', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('third_party_sale', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('third_party_sale', 'selling_price')
    op.drop_column('third_party_sale', 'purchase_price')
    op.drop_column('third_party_sale', 'profit_per_unit')
    op.drop_column('third_party_sale', 'sale_date')
    op.drop_column('third_party_sale', 'quantity')
    op.drop_column('third_party_sale', 'medicine_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('third_party_sale', sa.Column('medicine_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('third_party_sale', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('third_party_sale', sa.Column('sale_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('third_party_sale', sa.Column('profit_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('third_party_sale', sa.Column('purchase_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('third_party_sale', sa.Column('selling_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('third_party_sale', 'date')
    op.drop_column('third_party_sale', 'sale_price')
    op.drop_column('third_party_sale', 'buying_price')
    # ### end Alembic commands ###
